apiVersion: v1
kind: Service
metadata:
  name: photogalleryy
  labels:
    run: photogalleryy
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30036
      name: http
  selector:
    run: photogalleryy
