apiVersion: apps/v1
kind: Deployment
metadata:
  name: photogalleryy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: photogalleryy
  template:
    metadata:
      labels:
        run: photogalleryy
    spec:
      containers:
      - name: photogalleryy
        image: bhargava272/reactapp:v2
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

