apiVersion: apps/v1
kind: Deployment
metadata:
  name: photogallery
spec:
  selector:
    matchLabels:
      run: photogallery
  template:
    metadata:
      labels:
        run: photogallery
    spec:
      containers:
      - name: photogallery
        image: bhargava272/reactapp:v2
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

